# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python für Historiker:innen - Intermediate
author: <a href="https://www.geschichte.hu-berlin.de/de/bereiche-und-lehrstuehle/digital-history">Digital History, Humboldt-Universität zu Berlin</a> 
copyright: "2024"
logo: img/Logo_DigitalHistoryBerlin.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: python-basics-jb-book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# If GitLab is your version control system, you can use this to link to your repository
# Note: Live Code and Binder links will not work with GitLab currently
sphinx:
 recursive_update: true
 config:
    html_context:
      default_mode: light
    html_theme_options:
      announcement: <p class="banner">⚠️ Preview (beta 0.0.1)</p>
      #show_version_warning_banner: True
      logo: 
        image_light: img/Logo_DigitalHistoryBerlin.png
        image_dark: img/Logo_DigitalHistoryBerlin_dark.png
 #    repository_provider: "gitlab"

# Information about where the book exists on the web
repository:
  url: https://github.com/Digital-History-Berlin/Python-fuer-Historiker-innen-Intermediate  # Online location of your book
  #path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: 
    <div>
    Zitierempfehlung
    </div>
    <div>
    Melanie Althage, Martin Dröge, Sophie Eckenstaler, Torsten Hiltmann, Philipp Schneider, Python für Historiker:innen - Intermediate, 20.05.2024, Jupyter Book, (v1.0), <a href="https://digital-history-berlin.github.io/Python-fuer-Historiker-innen/home.html">https://digital-history-berlin.github.io/Python-fuer-Historiker-innen/home.html</a>,  <a href="https://doi.org/10.5281/zenodo.6868043">https://doi.org/10.5281/zenodo.6868043</a>
    </div>
    <div>
    <a href="http://creativecommons.org/licenses/by/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons BY 4.0 License</a>.
    </div>

launch_buttons:
  notebook_interface: classic
  binderhub_url: "https://mybinder.org"
  #colab_url: "https://colab.research.google.com"
  #jupyterhub_url: "https://jupyterhub.hu-berlin.de" # needs additional JupyterLab exentensions: https://jupyterbook.org/en/stable/interactive/launchbuttons.html#add-a-launch-on-jupyterhub-button
  thebe: true
